---
led_low: 475
led_high: 650
led_eat: 400
IR_goal: 0.8
IR_err: 0.1

start_search_time: 500

modify_back_time: 1
modify_stop_time: 2
modify_turn_time: 5
modify_turn_time_back: 13

find_mouth_advance_time: 1000
